alias:
  helloworld:
    - cmd: 'echo "{{ greeting }}, {{ target }}!"'
      render_engine: inja
      template_vars:
        greeting: Hello
        target: World

  dotnetcode:
    - cmd: |
        #:package Humanizer@2.14.1

        using System;
        using System.Linq;
        using Humanizer;

        var currentDirectory = Environment.CurrentDirectory;
        var timeToMidnight = new DateTime(DateTime.Now.Year, DateTime.Now.Month, DateTime.Now.Day, 0, 0, 0).AddDays(1) - DateTime.Now;

        Console.WriteLine($"Current Directory: {currentDirectory}");
        Console.WriteLine($"Time to Midnight: {timeToMidnight.Humanize()}");

      execution_engine: dotnet_run

  luacode:
    - cmd: |
        local t = {}
        for str in string.gmatch(TEMPLATE_VARS.values, '([^,]+)') do
            table.insert(t, tonumber(str))
        end

        local sum = 0
        for k,v in pairs(t) do
            sum = sum + v
        end

        print(tostring(sum))

        return 0
      execution_engine: lua
      template_vars:
        values: "0"

  luacpr:
    - cmd: |
        local get = cpr.get("https://httpbin.org/get", { [ "a" ] = "b" }, { [ "Content-Type" ] = "application/json" })
        print("HTTP GET Response: " .. get.body)

        local post = cpr.post("https://httpbin.org/post", json.dump({ "a", "b" }), { [ "x" ] = "y" }, { [ "Content-Type" ] = "application/json" })
        print("HTTP POST Response: " .. post.body)
      execution_engine: lua
      template_vars:
        values: "0"

  luadump:
    - cmd: |
        function dump(o)
           if type(o) == 'table' then
              local s = '{ '
              for k,v in pairs(o) do
                 if type(k) ~= 'number' then k = '"'..k..'"' end
                 s = s .. '['..k..'] = ' .. dump(v) .. ','
              end
              return s .. '} '
           else
              return tostring(o)
           end
        end

        print("TEMPLATE_VARS:")
        print(dump(TEMPLATE_VARS))

        print("ENVS:")
        print(dump(ENVS))

        print("CTX:")
        print(dump(CTX))

        local j = '{ "key": "value", "number": 42, "nested": { "a": 1, "b": 2 } }'
        local parsed = json.parse(j)
        print("JSON parsed:")
        print(#parsed)
        print(dump(parsed))
      execution_engine: lua
      env:
        EXAMPLE_ENV_VAR: example_value

  build:
    - cmd: "cmake . --preset {{ preset }} --fresh && cmake --build build/"
      constraints:
        - osfamily: unix
      render_engine: inja
      template_vars:
        preset: default

    - cmd: |
        & '{{ vcvarsall_dir }}\vcvarsall.bat' {{ arch }};
        if ($?) {
            cmake . --preset {{ preset }} --fresh;
            if ($?) {
                cmake --build build/;
            }
        }
      constraints:
        - osfamily: windows
      render_engine: inja
      template_vars:
        vcvarsall_dir: 'C:\Program Files\Microsoft Visual Studio\18\Community\VC\Auxiliary\Build'
        arch: arm64
        preset: default

  test:
    - cmd: |
        cmake . --preset testing --fresh && cmake --build build/ &&
        ctest --output-on-failure --test-dir build/tests
      constraints:
        - osfamily: unix

    - cmd: |
        & '{{ vcvarsall_dir }}\vcvarsall.bat' {{ arch }};
        if ($?) {
            cmake . --preset testing --fresh;
            if ($?) {
                cmake --build build/;
                if ($?) {
                    ctest --output-on-failure --test-dir build/tests;
                }
            }
        }
      constraints:
        - osfamily: windows
      render_engine: inja
      template_vars:
        vcvarsall_dir: 'C:\Program Files\Microsoft Visual Studio\18\Community\VC\Auxiliary\Build'
        arch: arm64

  path:
    - cmd: "echo $PATH"
      constraints:
        - osfamily: unix

    - cmd: "echo $Env:Path"
      constraints:
        - osfamily: windows

  install:
    - cmd: sudo rm -f /usr/local/bin/xx && sudo cp build/xx/xx /usr/local/bin/xx
      constraints:
        - osfamily: unix
      requires_confirmation: true

    - cmd: Copy-Item -Path build/xx/xx.exe -Destination C:/tools/xx-cli/xx.exe -Force
      constraints:
        - osfamily: windows
      requires_confirmation: true

  htop:
    - cmd: htop
      constraints:
        - osfamily: unix

  ntop:
    - cmd: ntop
      constraints:
        - osfamily: windows

  downloads:
    - cmd: "yazi ~/Downloads"
      constraints:
        - osfamily: unix
